# Libraries

In [15]:
import numpy as np
import pandas as pd
from imblearn.over_sampling import RandomOverSampler
from sklearn.feature_selection import chi2
from sklearn.decomposition import PCA
from sklearn.feature_selection import SelectKBest
from sklearn.preprocessing import StandardScaler

# Load the dataset

In [16]:
data=pd.read_csv("gun-violence-data_01-2013_03-2018.csv")
data.head()

,incident_id,date,state,city_or_county,address,n_killed,n_injured,incident_url,source_url,incident_url_fields_missing,...,participant_age,participant_age_group,participant_gender,participant_name,participant_relationship,participant_status,participant_type,sources,state_house_district,state_senate_district
0,461105,2013-01-01,Pennsylvania,Mckeesport,1506 Versailles Avenue and Coursin Street,0,4,http://www.gunviolencearchive.org/incident/461105,http://www.post-gazette.com/local/south/2013/0...,False,...,0::20,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male||1::Male||3::Male||4::Female,0::Julian Sims,NaN,0::Arrested||1::Injured||2::Injured||3::Injure...,0::Victim||1::Victim||2::Victim||3::Victim||4:...,http://pittsburgh.cbslocal.com/2013/01/01/4-pe...,NaN,NaN
1,460726,2013-01-01,California,Hawthorne,13500 block of Cerise Avenue,1,3,http://www.gunviolencearchive.org/incident/460726,http://www.dailybulletin.com/article/zz/201301...,False,...,0::20,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male,0::Bernard Gillis,NaN,0::Killed||1::Injured||2::Injured||3::Injured,0::Victim||1::Victim||2::Victim||3::Victim||4:...,http://losangeles.cbslocal.com/2013/01/01/man-...,62.0,35.0
2,478855,2013-01-01,Ohio,Lorain,1776 East 28th Street,1,3,http://www.gunviolencearchive.org/incident/478855,http://chronicle.northcoastnow.com/2013/02/14/...,False,...,0::25||1::31||2::33||3::34||4::33,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male||1::Male||2::Male||3::Male||4::Male,0::Damien Bell||1::Desmen Noble||2::Herman Sea...,NaN,"0::Injured, Unharmed, Arrested||1::Unharmed, A...",0::Subject-Suspect||1::Subject-Suspect||2::Vic...,http://www.morningjournal.com/general-news/201...,56.0,13.0
3,478925,2013-01-05,Colorado,Aurora,16000 block of East Ithaca Place,4,0,http://www.gunviolencearchive.org/incident/478925,http://www.dailydemocrat.com/20130106/aurora-s...,False,...,0::29||1::33||2::56||3::33,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Female||1::Male||2::Male||3::Male,0::Stacie Philbrook||1::Christopher Ratliffe||...,NaN,0::Killed||1::Killed||2::Killed||3::Killed,0::Victim||1::Victim||2::Victim||3::Subject-Su...,http://denver.cbslocal.com/2013/01/06/officer-...,40.0,28.0
4,478959,2013-01-07,North Carolina,Greensboro,307 Mourning Dove Terrace,2,2,http://www.gunviolencearchive.org/incident/478959,http://www.journalnow.com/news/local/article_d...,False,...,0::18||1::46||2::14||3::47,0::Adult 18+||1::Adult 18+||2::Teen 12-17||3::...,0::Female||1::Male||2::Male||3::Female,0::Danielle Imani Jameison||1::Maurice Eugene ...,3::Family,0::Injured||1::Injured||2::Killed||3::Killed,0::Victim||1::Victim||2::Victim||3::Subject-Su...,http://myfox8.com/2013/01/08/update-mother-sho...,62.0,27.0

In [17]:
data= data.sample(n=23000, random_state=42)
data.to_csv("data.csv", index=False)

In [18]:
data.head()

,incident_id,date,state,city_or_county,address,n_killed,n_injured,incident_url,source_url,incident_url_fields_missing,...,participant_age,participant_age_group,participant_gender,participant_name,participant_relationship,participant_status,participant_type,sources,state_house_district,state_senate_district
194815,875588,2017-06-25,Virginia,Richmond,3500 block of Moody Avenue,0,1,http://www.gunviolencearchive.org/incident/875588,http://wric.com/2017/06/25/man-suffers-non-lif...,False,...,NaN,0::Adult 18+,0::Male,NaN,NaN,0::Injured,0::Victim,http://wric.com/2017/06/25/man-suffers-non-lif...,69.0,16.0
154177,690013,2016-10-31,Texas,Amarillo,3100 block of Oak Drive,1,0,http://www.gunviolencearchive.org/incident/690013,http://www.newschannel10.com/story/33525135/po...,False,...,0::25||1::18,0::Adult 18+||1::Adult 18+,0::Male||1::Male,0::Kharyi Nichols,NaN,0::Killed||1::Unharmed,0::Victim||1::Subject-Suspect,http://www.newschannel10.com/story/33525135/po...,87.0,31.0
168408,758027,2017-01-23,South Carolina,Charleston,1704 N Woodmere Dr,0,1,http://www.gunviolencearchive.org/incident/758027,http://abcnews4.com/news/crime-news/3-men-arre...,False,...,0::24||1::18||2::18,0::Adult 18+||1::Adult 18+||2::Adult 18+,0::Male||1::Male||2::Male,0::Joshua Davis||1::Antwan Grant||2::Malik Was...,NaN,"0::Injured||1::Unharmed, Arrested||2::Unharmed...",0::Victim||1::Subject-Suspect||2::Subject-Suspect,http://www.wmbfnews.com/story/34324458/cops-gu...,119.0,41.0
31176,173858,2014-08-12,Tennessee,Chattanooga,1117 E. Third St.,0,0,http://www.gunviolencearchive.org/incident/173858,http://www.timesfreepress.com/news/2014/aug/13...,False,...,1::27||2::36,NaN,NaN,1::Rodrick Smith||2::Kevin Perkins,NaN,NaN,0::Victim||1::Subject-Suspect||2::Subject-Suspect,http://www.timesfreepress.com/news/2014/aug/13...,28.0,10.0
91346,419030,2015-09-23,Pennsylvania,Philadelphia,7600 Sherwood Road,1,0,http://www.gunviolencearchive.org/incident/419030,http://6abc.com/news/man-killed-in-overbrook-p...,False,...,0::41,0::Adult 18+,0::Male,NaN,NaN,0::Killed,0::Victim,http://6abc.com/news/man-killed-in-overbrook-p...,NaN,NaN

## Columns

In [19]:
print(data.dtypes)

incident_id                      int64
date                            object
state                           object
city_or_county                  object
address                         object
n_killed                         int64
n_injured                        int64
incident_url                    object
source_url                      object
incident_url_fields_missing       bool
congressional_district         float64
gun_stolen                      object
gun_type                        object
incident_characteristics        object
latitude                       float64
location_description            object
longitude                      float64
n_guns_involved                float64
notes                           object
participant_age                 object
participant_age_group           object
participant_gender              object
participant_name                object
participant_relationship        object
participant_status              object
participant_type                object
sources                         object
state_house_district           float64
state_senate_district          float64
dtype: object

In [20]:
cols=data.columns.tolist()
cols

['incident_id',
 'date',
 'state',
 'city_or_county',
 'address',
 'n_killed',
 'n_injured',
 'incident_url',
 'source_url',
 'incident_url_fields_missing',
 'congressional_district',
 'gun_stolen',
 'gun_type',
 'incident_characteristics',
 'latitude',
 'location_description',
 'longitude',
 'n_guns_involved',
 'notes',
 'participant_age',
 'participant_age_group',
 'participant_gender',
 'participant_name',
 'participant_relationship',
 'participant_status',
 'participant_type',
 'sources',
 'state_house_district',
 'state_senate_district']

## Handle missing data (imputation, dropping rows/columns)

*Imputation*

In [21]:
numCols = ['n_killed', 'n_injured', 'latitude', 'longitude', 'n_guns_involved']
data[numCols] = data[numCols].fillna(data[numCols].mean())
catCols = ['state', 'city_or_county', 'gun_stolen', 'gun_type', 'incident_characteristics']
data[catCols] = data[catCols].fillna(data[catCols].mode().iloc[0])

*Dropping Column*

In [22]:
dataDropna = data.dropna()
dataDropnaColumns = data.dropna(axis=1)

Result

In [23]:
print("Summary statistics after handling missing data:")
print("Number of rows before dropping:", len(data))
print("Number of rows after dropping:", len(dataDropna))
print("Number of columns before dropping:", len(data.columns))
print("Number of columns after dropping:", len(dataDropnaColumns.columns))

Summary statistics after handling missing data:
Number of rows before dropping: 23000
Number of rows after dropping: 116
Number of columns before dropping: 29
Number of columns after dropping: 14

## Check for class imbalance (O)

In [24]:
print("Class imbalance for 'n_killed':")
print(data['n_killed'].value_counts())
print("\nClass imbalance for 'n_injured':")
print(data['n_injured'].value_counts())

Class imbalance for 'n_killed':
n_killed
0    17825
1     4625
2      470
3       62
4       12
5        2
9        1
7        1
8        1
6        1
Name: count, dtype: int64

Class imbalance for 'n_injured':
n_injured
0     13702
1      7870
2      1066
3       243
4        72
5        27
7         8
6         7
15        1
9         1
8         1
10        1
13        1
Name: count, dtype: int64

In [25]:
X = data.drop(['n_killed',], axis=1)  # Assuming 'n_killed' and 'n_injured' are the target variables
y = data[['n_killed']]
oversampler = RandomOverSampler(random_state=42)
X_resampled, y_resampled = oversampler.fit_resample(X, y)
data = pd.concat([pd.DataFrame(X_resampled, columns=X.columns), pd.DataFrame(y_resampled, columns=['n_killed'])], axis=1)

## Feature selection and dimensionality reduction (O)

Feature selection

In [26]:
data.dropna(inplace=True)
numFeatures = data.select_dtypes(include=['int64', 'float64']).drop(['incident_id'], axis=1)
# Numeric Features who are -ve --> +ve
numFeaturesPos = numFeatures.abs()
#chi square
selector = SelectKBest(score_func=chi2, k=8)
X_selected = selector.fit_transform(numFeaturesPos, data['n_killed'])
#New Features
newFeatures = numFeaturesPos.columns[selector.get_support()]

In [27]:
print(newFeatures)

Index(['n_injured', 'congressional_district', 'latitude', 'longitude',
       'n_guns_involved', 'state_house_district', 'state_senate_district',
       'n_killed'],
      dtype='object')

Dimensionality reduction

In [28]:
#Standardizing before PCA
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_selected)
#PCA
#Target to get 5 columns
pca = PCA(n_components=5)
X_pca = pca.fit_transform(X_scaled)
#reduced data Data Frame
newdata = pd.DataFrame(X_pca, columns=['PCA1', 'PCA2','PCA3', 'PCA4','PCA5'])
newdata

          PCA1      PCA2      PCA3      PCA4      PCA5
0    -0.902579  2.027094  3.400004 -1.368897  0.704606
1    -1.409030  1.907888 -2.133394 -0.880813 -0.389832
2    -0.436158  1.664019 -0.606486 -0.733160 -0.274480
3    -0.009318  0.601023  0.374455 -0.361374  0.771345
4    -0.680675  0.574758  1.888767  1.116861  0.540303
...        ...       ...       ...       ...       ...
1358 -0.568681 -1.926161  0.225271  0.112712 -0.049799
1359  2.750651  0.287678 -0.304358  0.198272  0.125859
1360 -0.568681 -1.926161  0.225271  0.112712 -0.049799
1361  2.750651  0.287678 -0.304358  0.198272  0.125859
1362  2.750651  0.287678 -0.304358  0.198272  0.125859

[1363 rows x 5 columns]

## Identify potential outliers and anomalies (o)

Z score

In [29]:
mean = newdata.mean()
std = newdata.std()
#Z Score
z_scores = ((newdata - mean) / std).abs()
#threshold
threshold = 5
#outliers
outliers = z_scores > threshold
outliers

       PCA1   PCA2   PCA3   PCA4   PCA5
0     False  False  False  False  False
1     False  False  False  False  False
2     False  False  False  False  False
3     False  False  False  False  False
4     False  False  False  False  False
...     ...    ...    ...    ...    ...
1358  False  False  False  False  False
1359  False  False  False  False  False
1360  False  False  False  False  False
1361  False  False  False  False  False
1362  False  False  False  False  False

[1363 rows x 5 columns]

In [30]:
newdata = newdata.mask(outliers).dropna()
newdata

          PCA1      PCA2      PCA3      PCA4      PCA5
0    -0.902579  2.027094  3.400004 -1.368897  0.704606
1    -1.409030  1.907888 -2.133394 -0.880813 -0.389832
2    -0.436158  1.664019 -0.606486 -0.733160 -0.274480
3    -0.009318  0.601023  0.374455 -0.361374  0.771345
4    -0.680675  0.574758  1.888767  1.116861  0.540303
...        ...       ...       ...       ...       ...
1358 -0.568681 -1.926161  0.225271  0.112712 -0.049799
1359  2.750651  0.287678 -0.304358  0.198272  0.125859
1360 -0.568681 -1.926161  0.225271  0.112712 -0.049799
1361  2.750651  0.287678 -0.304358  0.198272  0.125859
1362  2.750651  0.287678 -0.304358  0.198272  0.125859

[1344 rows x 5 columns]

In [32]:
newdata.head

<bound method NDFrame.head of           PCA1      PCA2      PCA3      PCA4      PCA5
0    -0.902579  2.027094  3.400004 -1.368897  0.704606
1    -1.409030  1.907888 -2.133394 -0.880813 -0.389832
2    -0.436158  1.664019 -0.606486 -0.733160 -0.274480
3    -0.009318  0.601023  0.374455 -0.361374  0.771345
4    -0.680675  0.574758  1.888767  1.116861  0.540303
...        ...       ...       ...       ...       ...
1358 -0.568681 -1.926161  0.225271  0.112712 -0.049799
1359  2.750651  0.287678 -0.304358  0.198272  0.125859
1360 -0.568681 -1.926161  0.225271  0.112712 -0.049799
1361  2.750651  0.287678 -0.304358  0.198272  0.125859
1362  2.750651  0.287678 -0.304358  0.198272  0.125859

[1344 rows x 5 columns]>

In [33]:
data.head

<bound method NDFrame.head of        incident_id        date      state city_or_county  \
118         808580  2017-02-24    Florida  Pompano Beach
571         741494  2017-01-01      Idaho      Pocatello
668         737504  2016-12-29     Kansas        Wichita
1727        917188  2017-08-17  Louisiana    Baton Rouge
2515        605105  2016-07-16    Florida        Oldsmar
...            ...         ...        ...            ...
71288       812491  2017-04-05    Florida   Jacksonville
71291       262147  2014-12-12    Georgia          Macon
71295       812491  2017-04-05    Florida   Jacksonville
71316       262147  2014-12-12    Georgia          Macon
71317       262147  2014-12-12    Georgia          Macon

                     address  n_injured  \
118          901 W Sample Rd          0
571            Cemetery Road          0
668           5400 E 21st St          0
1727      Sherwood Hollow Ct          1
2515        40 Pelican Drive          0
...                      ...        ...
71288       12171 Beach Blvd          0
71291  2822 Bloomfield Drive          3
71295       12171 Beach Blvd          0
71316  2822 Bloomfield Drive          3
71317  2822 Bloomfield Drive          3

                                            incident_url  \
118    http://www.gunviolencearchive.org/incident/808580
571    http://www.gunviolencearchive.org/incident/741494
668    http://www.gunviolencearchive.org/incident/737504
1727   http://www.gunviolencearchive.org/incident/917188
2515   http://www.gunviolencearchive.org/incident/605105
...                                                  ...
71288  http://www.gunviolencearchive.org/incident/812491
71291  http://www.gunviolencearchive.org/incident/262147
71295  http://www.gunviolencearchive.org/incident/812491
71316  http://www.gunviolencearchive.org/incident/262147
71317  http://www.gunviolencearchive.org/incident/262147

                                              source_url  \
118    http://sheriff.org/posts/post.cfm?id=41490D00-...
571    http://www.idahostatejournal.com/news/local/fo...
668    http://www.kfdi.com/news/man-shoots-alleged-bu...
1727   http://www.theadvocate.com/baton_rouge/news/cr...
2515   http://www.fox13news.com/news/local-news/17535...
...                                                  ...
71288  http://www.actionnewsjax.com/news/local/jackso...
71291  http://www.macon.com/2015/06/16/3799996/new-su...
71295  http://www.actionnewsjax.com/news/local/jackso...
71316  http://www.macon.com/2015/06/16/3799996/new-su...
71317  http://www.macon.com/2015/06/16/3799996/new-su...

       incident_url_fields_missing  congressional_district  ...  \
118                          False                    21.0  ...
571                          False                     2.0  ...
668                          False                     4.0  ...
1727                         False                     6.0  ...
2515                         False                    12.0  ...
...                            ...                     ...  ...
71288                        False                     4.0  ...
71291                        False                     2.0  ...
71295                        False                     4.0  ...
71316                        False                     2.0  ...
71317                        False                     2.0  ...

                                   participant_age_group  \
118                           0::Adult 18+||1::Adult 18+
571                                         1::Adult 18+
668                           0::Adult 18+||1::Adult 18+
1727   0::Adult 18+||1::Teen 12-17||2::Adult 18+||3::...
2515                          0::Adult 18+||1::Adult 18+
...                                                  ...
71288           0::Adult 18+||1::Adult 18+||2::Adult 18+
71291  0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...
71295           0::Adult 18+||1::Adult 18+||2::Adult 18+
71316  0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...
71317  0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...

                                      participant_gender  \
118                                     0::Male||1::Male
571                                              1::Male
668                                     0::Male||1::Male
1727                  0::Male||1::Male||2::Male||3::Male
2515                                    0::Male||1::Male
...                                                  ...
71288                      0::Female||1::Female||2::Male
71291  0::Male||1::Male||2::Male||3::Female||4::Male|...
71295                      0::Female||1::Female||2::Male
71316  0::Male||1::Male||2::Male||3::Female||4::Male|...
71317  0::Male||1::Male||2::Male||3::Female||4::Male|...

                                        participant_name  \
118                                     0::Robin Francis
571                               1::Heath "Petey" Dixey
668                                      0::Robert Young
1727   0::Jywuan Butler||2::Jamoriya Ben||3::Kenneth ...
2515               0::Edwin H Barthold||1::Steven Larson
...                                                  ...
71288  0::Elizabeth Lorinda Rush||1::Elizabeth Christ...
71291  0::Cory Hollingshed||1::George Henley||2::Derr...
71295  0::Elizabeth Lorinda Rush||1::Elizabeth Christ...
71316  0::Cory Hollingshed||1::George Henley||2::Derr...
71317  0::Cory Hollingshed||1::George Henley||2::Derr...

                                participant_relationship  \
118                                     1::Armed Robbery
571                                            1::Family
668                                           1::Friends
1727                  2::Armed Robbery||3::Armed Robbery
2515                                         1::Neighbor
...                                                  ...
71288                                          2::Family
71291  4::Gang vs Gang||5::Gang vs Gang||6::Gang vs G...
71295                                          2::Family
71316  4::Gang vs Gang||5::Gang vs Gang||6::Gang vs G...
71317  4::Gang vs Gang||5::Gang vs Gang||6::Gang vs G...

                                      participant_status  \
118                             0::Unharmed||1::Unharmed
571                               0::Unharmed||1::Killed
668                               0::Killed||1::Arrested
1727     0::Killed||1::Injured||2::Arrested||3::Arrested
2515                                0::Killed||1::Killed
...                                                  ...
71288                    0::Killed||1::Killed||2::Killed
71291  0::Killed||1::Killed||2::Killed||3::Injured||4...
71295                    0::Killed||1::Killed||2::Killed
71316  0::Killed||1::Killed||2::Killed||3::Injured||4...
71317  0::Killed||1::Killed||2::Killed||3::Injured||4...

                                        participant_type  \
118                        0::Victim||1::Subject-Suspect
571                        0::Victim||1::Subject-Suspect
668                        0::Victim||1::Subject-Suspect
1727   0::Victim||1::Victim||2::Subject-Suspect||3::S...
2515                       0::Victim||1::Subject-Suspect
...                                                  ...
71288           0::Victim||1::Victim||2::Subject-Suspect
71291  0::Victim||1::Victim||2::Victim||3::Victim||4:...
71295           0::Victim||1::Victim||2::Subject-Suspect
71316  0::Victim||1::Victim||2::Victim||3::Victim||4:...
71317  0::Victim||1::Victim||2::Victim||3::Victim||4:...

                                                 sources state_house_district  \
118    http://www.sun-sentinel.com/local/broward/deer...                 92.0
571    http://www.idahostatejournal.com/news/local/fo...                 28.0
668    http://www.kwch.com/content/news/One-criticall...                 89.0
1727   http://www.wbrz.com/news/one-suspect-in-custod...                101.0
2515   http://www.pcsoweb.com/16-163-detectives-condu...                 64.0
...                                                  ...                  ...
71288  http://www.news4jax.com/news/jso-shooting-repo...                 12.0
71291  http://www.macon.com/2014/12/12/3476102/2-men-...                142.0
71295  http://www.news4jax.com/news/jso-shooting-repo...                 12.0
71316  http://www.macon.com/2014/12/12/3476102/2-men-...                142.0
71317  http://www.macon.com/2014/12/12/3476102/2-men-...                142.0

      state_senate_district n_killed
118                    29.0        0
571                    28.0        1
668                    29.0        1
1727                   15.0        1
2515                   20.0        2
...                     ...      ...
71288                   4.0        3
71291                  26.0        3
71295                   4.0        3
71316                  26.0        3
71317                  26.0        3

[1363 rows x 29 columns]>